### ISSUE TITLE
Network card problem

### ISSUE THREAD

**Issue by 871451db** [trgcyln/Lenovo-Hackintosh#1]
After installing the bcm94360cs2 network card, there is a problem with the wifi link and it does not work properly. The network speed is unstable after replacing some drivers.

**Comment by trgcyln** [comment]
Hello,
First try to turn off your Wifi.

Then go to /Library/Preferences/SystemConfiguration/ folder.
Find these files and delete them:
(remember to backup)

- com.apple.airport.preferences.plist
- com.apple.wifi.message-tracer.plist
- NetworkInterfaces.plist
- preferences.plist

and restart.

Share me the results.
