### ISSUE TITLE
Lenovo Ideapad 510-15IKB OpenCore Battery Status not working

### ISSUE THREAD

**Issue by ghost** [trgcyln/Lenovo-Hackintosh#4]
Hi, 
I have the exact same Laptop Model as you, and still after following along i can't get Battery Read Outs once MacOS Boots without the Install USB. In Recovery Mode it somehow works? I already tried fixing it with the solutions given on the official OpenCore page, but it didn't work. My question is: How did you manage to fix it?/ What can you recommend me to try out so Battery Read Outs will eventually work? 

Thanks in advance!

**Comment by trgcyln** [comment]
Hello, I've never tried to install OpenCore. OpenCore  files belong @AgentFabulous 
Perhaps, he can help you with this problem.  All I can say is that you can try DSDT patches to make the battery readings work. Other than that, I have no idea about the OpenCore environment. Sorry for my late response.

**Comment by ghost** [comment]
Okay thank you! Since you already mentioned the owner of the files i will wait for him to maybe respond before i write to him directly. I also ran into this weird bug that i couldn't update OC maybe AgentFabulous can help me out there as well.
